#!/bin/bash

# Initialize variables
SCRIPT_DIR="$(dirname "$0")"

VENV_PATH="$SCRIPT_DIR/ai-assist"
if [ ! -d "$VENV_PATH" ]; then
    python3 -m venv "$VENV_PATH"
    source "$VENV_PATH/bin/activate"
    pip install -r requirements.txt
else
    source "$VENV_PATH/bin/activate"
fi
if [ ! -z "$AI_MODEL" ]; then
    model="$AI_MODEL"
else
    model="gem"
fi

prompt="$*"

# Check if prompt is provided
if [ -z "$prompt" ]; then
    echo "Error: No prompt provided. Please provide a prompt as the first argument."
    exit 1
fi

cd $SCRIPT_DIR
python3 ai.py --prompt "$prompt" --model "$model" | python3 pretty.py
deactivate